export const disable = { table: { disable: true } };

export const disableOnEvent = {
    ref: disable,
    onAuxClick: disable,
    onAuxClickCapture: disable,
    onClick: disable,
    onDoubleClick: disable,
    onClickCapture: disable,
    onDoubleClickCapture: disable,
    onContextMenu: disable,
    onContextMenuCapture: disable,
    onMouseDown: disable,
    onMouseDownCapture: disable,
    onMouseEnter: disable,
    onMouseLeave: disable,
    onMouseMove: disable,
    onMouseMoveCapture: disable,
    onMouseOut: disable,
    onMouseOutCapture: disable,
    onMouseOver: disable,
    onMouseOverCapture: disable,
    onMouseUp: disable,
    onMouseUpCapture: disable,
    onFocus: disable,
    onFocusCapture: disable,
    onBlur: disable,
    onBlurCapture: disable,
    onChange: disable,
    onChangeCapture: disable,
    onBeforeInput: disable,
    onBeforeInputCapture: disable,
    onInput: disable,
    onInputCapture: disable,
    onReset: disable,
    onResetCapture: disable,
    onSubmit: disable,
    onSubmitCapture: disable,
    onInvalid: disable,
    onInvalidCapture: disable,
    onKeyDown: disable,
    onKeyDownCapture: disable,
    onKeyPress: disable,
    onKeyPressCapture: disable,
    onKeyUp: disable,
    onKeyUpCapture: disable,
};

export const crossOut = {
    control: {
        type: 'none',
    },
};
