name: 'ci'
on:
    pull_request:
        branches:
            - master
            - devel

jobs:
    test:
        name: 'Test'
        runs-on: 'ubuntu-latest'
        if: "!contains(github.event.head_commit.message,'#skip-ci')"

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
              uses: actions/setup-node@v1
            - run: yarn install
            - name: Typecheck
              run: yarn typecheck
            - name: Lint
              run: yarn lint
            - name: Validate dependency tree
              run: yarn validateDepsTree
            - name: Test
              run: yarn test
              env:
                  CI: true
